-- میز / Miz database schema
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  avatar_url text,
  bio text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  parent_id bigint references public.categories(id) on delete set null
);

create table if not exists public.needs (
  id uuid primary key default gen_random_uuid(),
  creator_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  description text not null,
  category_id bigint references public.categories(id) on delete set null,
  urgency text not null default 'normal' check (urgency in ('normal','medium','high')),
  budget_min numeric,
  budget_max numeric,
  needed_by date,
  is_recurring boolean not null default false,
  region text,
  status text not null default 'open' check (status in ('open','matched','closed','archived')),
  visibility text not null default 'public' check (visibility in ('public','community','private')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.need_groups (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  category_id bigint references public.categories(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.need_group_memberships (
  group_id uuid not null references public.need_groups(id) on delete cascade,
  need_id uuid not null references public.needs(id) on delete cascade,
  similarity_score numeric check (similarity_score between 0 and 1),
  primary key (group_id, need_id)
);

create table if not exists public.claims (
  id uuid primary key default gen_random_uuid(),
  author_id uuid references public.profiles(id) on delete set null,
  need_id uuid references public.needs(id) on delete set null,
  statement text not null,
  status text not null default 'unverified' check (status in ('unverified','under_review','partially_supported','supported','refuted','disputed')),
  confidence numeric check (confidence between 0 and 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sources (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  url text,
  publisher text,
  source_type text,
  published_at timestamptz,
  accessed_at timestamptz not null default now(),
  authority_level integer check (authority_level between 0 and 5),
  verified boolean not null default false
);

create table if not exists public.evidence (
  id uuid primary key default gen_random_uuid(),
  claim_id uuid not null references public.claims(id) on delete cascade,
  source_id uuid not null references public.sources(id) on delete cascade,
  relation text not null check (relation in ('supports','refutes','context')),
  excerpt text,
  strength numeric check (strength between 0 and 1),
  created_at timestamptz not null default now()
);

create table if not exists public.verifications (
  id uuid primary key default gen_random_uuid(),
  claim_id uuid not null references public.claims(id) on delete cascade,
  reviewer_id uuid references public.profiles(id) on delete set null,
  status text not null,
  confidence numeric check (confidence between 0 and 1),
  rationale text,
  reviewed_at timestamptz not null default now()
);

create table if not exists public.reputation_events (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  event_type text not null,
  target_type text,
  target_id uuid,
  value numeric not null,
  reason text,
  created_at timestamptz not null default now()
);

create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid references public.profiles(id) on delete set null,
  target_type text not null,
  target_id uuid not null,
  reason text not null,
  status text not null default 'open',
  created_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id uuid primary key default gen_random_uuid(),
  report_id uuid not null references public.reports(id) on delete cascade,
  reviewer_id uuid references public.profiles(id) on delete set null,
  decision text,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique
);

create table if not exists public.need_tags (
  need_id uuid not null references public.needs(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  primary key (need_id, tag_id)
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  kind text not null,
  payload jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  target_type text,
  target_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.needs enable row level security;
alter table public.claims enable row level security;
alter table public.sources enable row level security;
alter table public.evidence enable row level security;
alter table public.verifications enable row level security;
alter table public.reports enable row level security;
alter table public.reviews enable row level security;
alter table public.notifications enable row level security;
alter table public.audit_logs enable row level security;

-- Public reads for intentionally public records; writes will be restricted to authenticated flows.
create policy if not exists "public needs readable" on public.needs for select using (visibility = 'public');
create policy if not exists "public claims readable" on public.claims for select using (true);
create policy if not exists "public sources readable" on public.sources for select using (true);
create policy if not exists "public evidence readable" on public.evidence for select using (true);

-- Profile owners can manage their own profile.
create policy if not exists "profile owner read" on public.profiles for select using (auth.uid() = id);
create policy if not exists "profile owner update" on public.profiles for update using (auth.uid() = id);
